from __future__ import annotations
from pathlib import Path

from app.config import settings


class NginxRouteManager:
    def write_route(self, app_id: int, slug: str, host_port: int) -> None:
        config = f"""\
http:
  routers:
    app-{app_id}:
      rule: "PathPrefix(`/apps/{slug}`)"
      middlewares:
        - pe-auth
      service: app-{app_id}-svc
      priority: 5

  services:
    app-{app_id}-svc:
      loadBalancer:
        servers:
          - url: "http://{settings.host_ip}:{host_port}"
"""
        route_file = Path(settings.traefik_dynamic_dir) / f"app_{app_id}.yml"
        route_file.write_text(config)
        self._reload_nginx()

    def remove_route(self, app_id: int) -> None:
        route_file = Path(settings.traefik_dynamic_dir) / f"app_{app_id}.yml"
        if route_file.exists():
            route_file.unlink()
        self._reload_nginx()

    def _reload_nginx(self) -> None:
        try:
            traefik_dir = Path(settings.traefik_dynamic_dir)
            nginx_conf_lines = ["# Auto-generated by SpiderVerseAI backend\n"]

            for yml_file in sorted(traefik_dir.glob("app_*.yml")):
                content = yml_file.read_text()
                slug = None
                port = None
                for line in content.splitlines():
                    line = line.strip()
                    if line.startswith('rule:') and 'PathPrefix' in line:
                        start = line.find('/apps/') + 6
                        end = line.find('`', start)
                        if start > 5 and end > start:
                            slug = line[start:end]
                    if line.startswith('- url:'):
                        parts = line.split(':')
                        if len(parts) >= 3:
                            try:
                                port = int(parts[-1].strip().strip('"'))
                            except ValueError:
                                pass

                if slug and port:
                    nginx_conf_lines.append(f"""
location /apps/{slug}/ {{
    proxy_pass http://127.0.0.1:{port}/apps/{slug}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 86400;
}}
location /apps/{slug} {{
    return 301 /apps/{slug}/$is_args$args;
}}
""")

            nginx_apps_path = traefik_dir / "nginx-apps.conf"
            nginx_apps_path.write_text("".join(nginx_conf_lines))

            import docker as docker_sdk
            client = docker_sdk.from_env()
            container = client.containers.get("frontend")
            container.exec_run("nginx -s reload")
        except Exception:
            pass
