from __future__ import annotations
from typing import Optional, Protocol

from app.core.entities.app import AppEntity


class IAppRepo(Protocol):
    def get(self, app_id: int) -> Optional[AppEntity]: ...
    def get_by_slug(self, slug: str) -> Optional[AppEntity]: ...
    def list(self, page: int = 1, size: int = 20, status: Optional[str] = None) -> tuple[list[AppEntity], int]: ...
    def list_all(self) -> list[AppEntity]: ...
    def create(self, entity: AppEntity) -> AppEntity: ...
    def update(self, entity: AppEntity) -> AppEntity: ...
    def delete(self, app_id: int) -> None: ...
