from __future__ import annotations
from typing import Optional, Protocol


class IAuthProvider(Protocol):
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, plain: str, hashed: str) -> bool: ...
    def create_token(self, user_id: int, username: str, role: str, session_token: str = "") -> str: ...
    def decode_token(self, token: str) -> Optional[dict]: ...
