from __future__ import annotations
from typing import Optional, Protocol

from app.core.entities.config import ConfigEntity, ConfigHistoryEntity


class IConfigRepo(Protocol):
    def get(self, key: str) -> Optional[ConfigEntity]: ...
    def get_by_prefix(self, prefix: str) -> list[ConfigEntity]: ...
    def upsert(self, entity: ConfigEntity) -> ConfigEntity: ...
    def delete(self, key: str) -> bool: ...
    def add_history(self, entity: ConfigHistoryEntity) -> ConfigHistoryEntity: ...
    def get_history(self, key: str, limit: int = 20) -> list[ConfigHistoryEntity]: ...
