from typing import Protocol


class IContainerRuntime(Protocol):
    def build_and_run(self, app_id: int, slug: str, build_path: str) -> dict: ...
    def stop(self, container_name: str) -> None: ...
    def restart(self, container_name: str) -> None: ...
    def remove(self, container_name: str) -> None: ...
