from __future__ import annotations
from typing import Optional, Protocol

from app.core.entities.prompt import PromptEntity


class IPromptRepo(Protocol):
    def list(self, category: Optional[str] = None, active_only: bool = True) -> list[PromptEntity]: ...
    def list_categories(self) -> list[str]: ...
    def get(self, prompt_id: int) -> Optional[PromptEntity]: ...
    def create(self, entity: PromptEntity) -> PromptEntity: ...
    def update(self, entity: PromptEntity) -> PromptEntity: ...
    def delete(self, prompt_id: int) -> None: ...
