from __future__ import annotations
from pathlib import Path
from typing import Protocol


class IFileStorage(Protocol):
    def read_json_files(self, directory: Path, pattern: str = "*.json") -> list[dict]: ...
    def write_json(self, path: Path, data: dict) -> None: ...
    def list_files(self, directory: Path, recursive: bool = False) -> list[Path]: ...
    def read_json(self, path: Path) -> dict: ...
    def ensure_dir(self, path: Path) -> None: ...
    def remove_tree(self, path: Path) -> None: ...
    def file_exists(self, path: Path) -> bool: ...
    def file_stat(self, path: Path) -> dict: ...
