from __future__ import annotations
from typing import Optional, Protocol

from app.core.entities.user import UserEntity


class IUserRepo(Protocol):
    def get(self, user_id: int) -> Optional[UserEntity]: ...
    def get_by_username(self, username: str) -> Optional[UserEntity]: ...
    def get_batch(self, user_ids: list[int]) -> dict[int, UserEntity]: ...
    def list_all(self) -> list[UserEntity]: ...
    def create(self, entity: UserEntity) -> UserEntity: ...
    def update(self, entity: UserEntity) -> UserEntity: ...
    def delete(self, user_id: int) -> None: ...
    def count(self) -> int: ...
